name: Test Dockerfiles

on:
  pull_request:
    paths:
      - '**/Dockerfile'

permissions:
  contents: read
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build Stable Image
        if: hashFiles('stable/Dockerfile') != ''
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: stable/Dockerfile
          push: false
          load: true
          tags: debian-stable-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner on Stable Image
        if: hashFiles('stable/Dockerfile') != ''
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: 'debian-stable-test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Tests on Stable Image
        if: hashFiles('stable/Dockerfile') != ''
        run: |
          docker run --rm -v ${{ github.workspace }}/scripts:/scripts debian-stable-test bash /scripts/run-dummy-tests.sh

      - name: Build Unstable Image
        if: hashFiles('unstable/Dockerfile') != ''
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: unstable/Dockerfile
          push: false
          load: true
          tags: debian-unstable-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner on Unstable Image
        if: hashFiles('unstable/Dockerfile') != ''
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: 'debian-unstable-test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Tests on Unstable Image
        if: hashFiles('unstable/Dockerfile') != ''
        run: |
          docker run --rm -v ${{ github.workspace }}/scripts:/scripts debian-unstable-test bash /scripts/run-dummy-tests.sh
