name: Test Dockerfiles

on:
  pull_request:
    paths:
      - '**/Dockerfile'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Stable Image
        if: hashFiles('stable/Dockerfile') != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: stable/Dockerfile
          push: false
          load: true
          tags: debian-stable-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner on Stable Image
        if: hashFiles('stable/Dockerfile') != ''
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: 'debian-stable-test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Tests on Stable Image
        if: hashFiles('stable/Dockerfile') != ''
        run: |
          docker run --rm -v ${{ github.workspace }}/scripts:/scripts debian-stable-test bash /scripts/run-dummy-tests.sh

      - name: Build Unstable Image
        if: hashFiles('unstable/Dockerfile') != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: unstable/Dockerfile
          push: false
          load: true
          tags: debian-unstable-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner on Unstable Image
        if: hashFiles('unstable/Dockerfile') != ''
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: 'debian-unstable-test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Tests on Unstable Image
        if: hashFiles('unstable/Dockerfile') != ''
        run: |
          docker run --rm -v ${{ github.workspace }}/scripts:/scripts debian-unstable-test bash /scripts/run-dummy-tests.sh
