name: Test Dockerfiles

on:
  pull_request:
    paths:
      - '**/Dockerfile'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Stable Image
        run: |
          if [ -f stable/Dockerfile ]; then
            docker build -t debian-stable-test -f stable/Dockerfile .
          fi

      - name: Run Tests on Stable Image
        run: |
          if [ -f stable/Dockerfile ]; then
            docker run --rm -v ${{ github.workspace }}/scripts:/scripts debian-stable-test bash /scripts/run-dummy-tests.sh
          fi

      - name: Build Unstable Image
        run: |
          if [ -f unstable/Dockerfile ]; then
            docker build -t debian-unstable-test -f unstable/Dockerfile .
          fi

      - name: Run Tests on Unstable Image
        run: |
          if [ -f unstable/Dockerfile ]; then
            docker run --rm -v ${{ github.workspace }}/scripts:/scripts debian-unstable-test bash /scripts/run-dummy-tests.sh
          fi
